### ISSUE TITLE
add git add . in README file

### ISSUE THREAD

**Issue by gauravchauhan2403** [vinayaksh42/smvdu-codeclub#11]
## Description
Add a " git add . " statement before " git commit -m " statement.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by iFlameing** [comment]
I didn't think this is a relevant issue because sometimes you don't want to add all the files.

**Comment by gauravchauhan2403** [comment]
@iFlameing sir, I was facing the problem,so added this to issue. BTW thankyou for your guidance
