### ISSUE TITLE
Make navbar sticky and relevant.

### ISSUE THREAD

**Issue by codetheorem** [vinayaksh42/smvdu-codeclub#2]
## Description
Make navbar according to the image and also add tabs to it.

## Mocks

![image](https://user-images.githubusercontent.com/54779517/82590547-8291bc00-9bbb-11ea-874a-ebd5576af7f6.png)

### Update 
- [x] It should follow our color pallet and design

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by gauravchauhan2403** [comment]
Please assign this to me. I want to work on it.
