### ISSUE TITLE
Add social media icons in the footer

### ISSUE THREAD

**Issue by codetheorem** [vinayaksh42/smvdu-codeclub#27]
## Description
Add various social media icons in the footer

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by ronitsingh1405** [comment]
I can work on it :)

**Comment by gauravchauhan2403** [comment]
Assign this to me, i can work on it.

**Comment by ronitsingh1405** [comment]
I have added the social media links
