### ISSUE TITLE
Fix navbar

### ISSUE THREAD

**Issue by codetheorem** [vinayaksh42/smvdu-codeclub#30]
## Description
Fix and update navbar in all pages according to the landing page.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by ronitsingh1405** [comment]
Hey can u assign me....

**Comment by ronitsingh1405** [comment]
clarification needed - all page's navbar should be same as index.html page, right?

**Comment by codetheorem** [comment]
Yes @ronitsingh1405

**Comment by ronitsingh1405** [comment]
Hey I see that issue #19 is similar to this issue so maybe I can work on both at the same time :)

**Comment by codetheorem** [comment]
@ronitsingh1405 Ok join our discord server link is in readme for communication.
