### ISSUE TITLE
align the social media icon to center of footer

### ISSUE THREAD

**Issue by vinayaksh42** [vinayaksh42/smvdu-codeclub#8]
## Description
align the social media icon

## Mocks
![dghJCKkf6H](https://user-images.githubusercontent.com/54861487/82670187-46f9ff00-9c5a-11ea-97e5-40cdae343f4b.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by gauravchauhan2403** [comment]
assign it to me.
